safe_require("dap", function(dap)
  -- dap.set_log_level("DEBUG")
  vim.keymap.set("n", "<leader>db", "<cmd>lua require'dap'.toggle_breakpoint()<CR>")
  vim.keymap.set("n", "<leader>dB", function()
    vim.ui.input({ prompt = "Breakpoint condition" }, function(cond)
      if cond then
        dap.set_breakpoint(cond)
      end
    end)
  end)
  vim.keymap.set("n", "<leader>dc", "<cmd>lua require'dap'.continue()<CR>")
  vim.keymap.set("n", "<leader>dj", "<cmd>lua require'dap'.step_over()<CR>")
  vim.keymap.set("n", "<leader>di", "<cmd>lua require'dap'.step_into()<CR>")
  vim.keymap.set("n", "<leader>do", "<cmd>lua require'dap'.step_out()<CR>")
  vim.keymap.set("n", "<leader>dl", "<cmd>lua require'dap'.run_last()<CR>")
  vim.keymap.set("n", "<leader>dr", "<cmd>lua require'dap'.repl.open()<CR>")
  vim.keymap.set("n", "<leader>dq", "<cmd>lua require'dap'.terminate()<CR>")

  vim.fn.sign_define("DapBreakpoint", { text = "•", texthl = "DiagnosticError", linehl = "", numhl = "" })
  vim.fn.sign_define("DapBreakpointCondition", { text = "*", texthl = "DiagnosticError", linehl = "", numhl = "" })
  vim.fn.sign_define("DapLogPoint", { text = "⁋", texthl = "", linehl = "", numhl = "" })
  vim.fn.sign_define("DapStopped", { text = "→", texthl = "", linehl = "", numhl = "" })
  vim.fn.sign_define("DapBreakpointRejected", { text = "🛑", texthl = "", linehl = "", numhl = "" })
  safe_require("dapui", function(dapui)
    dapui.setup()
    dap.listeners.after.event_initialized["dapui_config"] = function()
      dapui.open()
    end
    dap.listeners.before.event_terminated["dapui_config"] = function()
      dapui.close()
    end
    dap.listeners.before.event_exited["dapui_config"] = function()
      dapui.close()
    end
  end)
  safe_require("dap-go").setup()
  safe_require("nvim-dap-virtual-text").setup()
  require("dap.ext.vscode").load_launchjs()
end)
