---
- name: Install requirements
  apt: name={{ item }} state=present
  sudo: true
  with_items:
    - python-pycurl

- name: Download Docker PPA key
  apt_key: url=https://get.docker.io/gpg
  sudo: true

- name: Add Docker PPA
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main'
  sudo: true

- name: Install common packages
  apt: name={{ item }} state=present
  sudo: true
  with_items:
    - ack-grep
    - coffeescript
    - curl
    - git-all
    - htop
    - ipython
    - openjdk-7-jre-headless
    - openssh-client
    - openssh-server
    - python-dev
    - python-pip
    - ruby
    - rubygems
    - tmux
    - unzip
    - vim-nox
    - xsel
    # For numpy & scipy
    - g++
    - gfortran
    - libatlas-base-dev
    # Misc
    - mplayer
    - tree
    - lxc-docker

- name: Install python packages
  pip: name={{ item }}
  sudo: true
  with_items:
    - virtualenv
    - autoenv

- name: Install ruby packages
  gem: name={{ item }} state=present
  sudo: true
  with_items:
    - mkrf

- name: Copy over dotfiles
  copy: src={{ item }} dest={{ ansible_env.HOME }}/{{ item }}
  with_items: dotfiles

- name: Copy over dotfiles in submodules
  synchronize: src={{ item }}
    dest={{ ansible_env.HOME }}
    delete=yes
  with_items: dotdirs

- name: compile command-t
  shell: ruby extconf.rb && make
    chdir={{ ansible_env.HOME }}/.vim/bundle/command-t/ruby/command-t

- name: Copy over scripts
  copy: src={{ item }} dest=/usr/local/bin/{{ item }}
  with_items: scripts
  sudo: true
